### ISSUE TITLE
Upload Limit Not Correctly Themed

### ISSUE THREAD

**Issue by PHILLJAY** [IEVEVO/darkcloud#3]
Hey love your theme btw

I just started uploading some mixes so I noticed the [You’re 98% to your upload limit](https://i.imgur.com/bSqo3LY.png) text is still unthemed. 
![firefox_2019-11-06_20-02-50](https://user-images.githubusercontent.com/47534916/68351166-a0407d80-00d0-11ea-942f-e7923e341c54.png)

I included a screenshot of what it looks like

**Comment by IEVEVO** [comment]
Fixed! Sorry for the wait, had to wait for one to appear before I could get the classes.
