### ISSUE TITLE
comments hard to read

### ISSUE THREAD

**Issue by mko9999** [IEVEVO/darkcloud#9]
recently there was a small website redesign on soundcloud causing comments to look like this, very hard to read.  any chance this could be fixed?

![image](https://github.com/IEVEVO/darkcloud/assets/149893548/3939c6dd-31d6-4fe9-9ae9-207a3f637d60)

**Comment by iamnotbobby** [comment]
idk if the maintainers are still alive but i made a fix for this in my pull request
you can manually _re-compile_ the extension if you know how to (if not, just let me know and i can help out)

**Comment by mko9999** [comment]
> idk if the maintainers are still alive but i made a fix for this in my pull request
> 
> you can manually _re-compile_ the extension if you know how to (if not, just let me know and i can help out)

i do not, could u help?

**Comment by iamnotbobby** [comment]
what browser are you using?

**Comment by mko9999** [comment]
firefox

**Comment by iamnotbobby** [comment]
> firefox

i'll let you know once firefox approves my addon listing

**Comment by IEVEVO** [comment]
Hi, super appreciate the help. Due to a back injury I am currently not able to work on this myself, unfortunately. Happy to merge pull requests when I get time though.

**Comment by iamnotbobby** [comment]
> Hi, super appreciate the help. Due to a back injury I am currently not able to work on this myself, unfortunately. Happy to merge pull requests when I get time though.

> firefox

👍
i've uploaded a temp fix on the addon hub for now

https://addons.mozilla.org/en-US/firefox/addon/soundcloud-dark-mode/

i'll take it down once you've merged the pull requests

**Comment by mko9999** [comment]
WOOWW tysmm<333

**Comment by IEVEVO** [comment]
Submitted - should be all good now, thank you all<3

**Comment by iamnotbobby** [comment]
Thank you. I'll take down the temporary addon.
